version : "3"
services:
    web:

      restart: always
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - "mysqldb"
    mysqldb:
      image: mysql
      restart: always
      environment:
        MYSQL_HOST: 'mysqldb'
        MYSQL_DATABASE: 'db_test'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'Passw0rd'
        MYSQL_ROOT_PASSWORD: 'R00t_Passw0ord!!'
      ports:
        - '3306:3306'